package media

import (
	"context"
	"encoding/binary"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"time"

	esphome "github.com/ygelfand/go-esphome-device"

	"github.com/HuskerMinion/techo5/echod/internal/hardware/speaker"
)

// Formats is what Home Assistant is asked to convert to. It runs the conversion through ffmpeg, so
// asking for plain WAV means no decoder here: strip the header and the rest is samples.
//
// Music gets the codec's own rate and both channels, so nothing is resampled and nothing is thrown
// away. Announcements stay at the pipeline's rate: they are one voice, and the bandwidth would buy
// nothing but a longer wait before the device says anything.
var Formats = []esphome.MediaFormat{
	{Format: "wav", SampleRate: speaker.Rate, Channels: speaker.Channels, SampleBytes: 2},
	{Format: "wav", SampleRate: speaker.VoiceRate, Channels: 1, SampleBytes: 2, Announcement: true},
}

// Tail is the silence added after speech, in milliseconds. Speech generated by a text to speech
// engine stops on its last sound with no silence after it, and the interpolating resampler needs a
// few samples beyond the end to run out. Without a tail the final word sounds cut off.
const Tail = 250

const fetchTimeout = 30 * time.Second

// Fetch downloads audio Home Assistant is serving and decodes it. The request carries the context, so
// silencing a sound abandons the download rather than leaving it to arrive and be thrown away.
func Fetch(ctx context.Context, url string) ([]int16, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}

	client := &http.Client{Timeout: fetchTimeout}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: %s", url, resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	samples, f, err := monoPCM(body)
	if err != nil {
		return nil, err
	}
	if f.channels != 1 || f.rate != speaker.VoiceRate {
		slog.Warn("announcement arrived in a format other than the one asked for; converted",
			"rate", f.rate, "channels", f.channels, "bits", f.bits, "url", url)
	}
	return samples, nil
}

// wavFormat is what the fmt chunk said.
type wavFormat struct {
	channels, rate, bits int
}

// monoPCM takes 16-bit samples out of a RIFF/WAVE body, walking the chunks rather than assuming a
// 44-byte header: a converted file can carry extra chunks before the data. The result is one channel
// at speaker.VoiceRate whatever the file carried: Home Assistant is asked for that, but what it
// serves is decided by its proxy, and a mismatch played as if it were right is speech at the wrong
// speed.
//
// Sizes are handled as uint64. A 32-bit int cannot hold a large RIFF size, and a chunk claiming
// one turns negative, which slips past a bounds check and panics on the slice.
func monoPCM(body []byte) ([]int16, wavFormat, error) {
	f := wavFormat{channels: 1, rate: speaker.VoiceRate, bits: 16}
	if len(body) < 12 || string(body[0:4]) != "RIFF" || string(body[8:12]) != "WAVE" {
		return nil, f, fmt.Errorf("not a WAVE file: %d bytes", len(body))
	}

	total := uint64(len(body))
	for off := uint64(12); off+8 <= total; {
		id := string(body[off : off+4])
		size := uint64(binary.LittleEndian.Uint32(body[off+4 : off+8]))
		off += 8

		end := off + size
		if end > total {
			end = total
		}

		switch id {
		case "fmt ":
			if end-off >= 16 {
				f.channels = int(binary.LittleEndian.Uint16(body[off+2:]))
				f.rate = int(binary.LittleEndian.Uint32(body[off+4:]))
				f.bits = int(binary.LittleEndian.Uint16(body[off+14:]))
			}
		case "data":
			if f.bits != 16 || f.channels < 1 {
				return nil, f, fmt.Errorf("unsupported WAVE: %d-bit, %d channels", f.bits, f.channels)
			}
			pcm := body[off:end]
			frames := len(pcm) / (2 * f.channels)
			mono := make([]int16, frames)
			for i := range mono {
				var sum int
				for c := 0; c < f.channels; c++ {
					sum += int(int16(binary.LittleEndian.Uint16(pcm[(i*f.channels+c)*2:])))
				}
				mono[i] = int16(sum / f.channels)
			}
			return toVoiceRate(mono, f.rate), f, nil
		}

		off = end
		if size%2 == 1 {
			off++
		}
	}
	return nil, f, fmt.Errorf("no data chunk in %d bytes", total)
}

// toVoiceRate brings mono speech to speaker.VoiceRate by linear interpolation, which is plenty for
// a voice that is about to be upsampled again on the way to the card.
func toVoiceRate(in []int16, rate int) []int16 {
	if rate == speaker.VoiceRate || rate <= 0 || len(in) < 2 {
		return in
	}
	n := int(int64(len(in)) * int64(speaker.VoiceRate) / int64(rate))
	out := make([]int16, n)
	step := float64(rate) / float64(speaker.VoiceRate)
	for i := range out {
		pos := float64(i) * step
		j := int(pos)
		if j >= len(in)-1 {
			out[i] = in[len(in)-1]
			continue
		}
		frac := pos - float64(j)
		out[i] = int16(float64(in[j])*(1-frac) + float64(in[j+1])*frac)
	}
	return out
}
